### ISSUE TITLE
Failure with XML viewer

### ISSUE THREAD

**Issue by Rosana-Lopez-UMU** [asmecher/pflPlugin#19]
In the journals portal of the University of Murcia (revistas.um.es) we have had to deactivate, for the moment, the **Publicacion facts plugin** because it generated an error with the **XML viewer plugin**. More specifically in the journal Anales de Documentación: https://revistas.um.es/analesdoc

This may be due to the plugin (pflPlugin) trying to add itself to the page that generates the viewer and that makes it stop working”.

We hope that this bug should be considered in PKP and fixed as soon as possible so that it can be implemented.

**Comment by asmecher** [comment]
@Rosana-Lopez-UMU, thanks for reporting; this appears to be a conflict with the Lens Reader plugin. You should be able to resolve the issue by applying the change in https://github.com/asmecher/pflPlugin/commit/d8c294399f6e614f09782a4993a0b6b33dbd0d5f to `plugins/generic/pflPlugin/PflPlugin.inc.php`. If you're able, please apply the change and confirm that it resolves the problem for you; I'll make sure the fix gets included in the next release of the plugin.
