### ISSUE TITLE
“External funding” displays ”No” when the funding plugin has not been installed

### ISSUE THREAD

**Issue by asmecher** [asmecher/pflPlugin#21]
The PFL item “External funding” displays ”No” when the funding plugin has not been installed. In such circumstances, items should read “N/A”.

**Comment by willinsky** [comment]
There is no bug. I failed to confirm the bug that was reported by checking the journal for which it was reported. I have now confirmed the other bug that was reported from this source on applying the label to non-peer-referred items.
